using System.Net;
using System.Net.Http.Headers;

namespace CCE.Api.IntegrationTests.Personas;

/// <summary>
/// Persona-matrix smoke. For each of the 6 user-role personas
/// (Anonymous + 5 Entra ID app roles) probe a representative set of
/// endpoints and assert the expected authorization outcome.
///
/// This test exercises the **authorization gate only** — does the
/// principal get past the per-permission policy? It does not assert
/// downstream business behavior (200 vs 404 vs 400 are all "passed
/// authorization"; only 401 / 403 are diagnostic).
///
/// Encoding:
/// <list type="bullet">
///   <item><c>Allowed</c> — expect NOT 401 AND NOT 403. Auth passed.</item>
///   <item><c>Forbidden</c> — expect 403. Auth succeeded but policy denied.</item>
///   <item><c>Anonymous</c> only — expect 401 when no token sent.</item>
/// </list>
///
/// The persona matrix is generated by combining
/// <see cref="Personas"/> × <see cref="Probes"/> and feeding xUnit's
/// <c>[MemberData]</c>.
/// </summary>
public sealed class PersonaMatrixTests :
    IClassFixture<CceTestWebApplicationFactory<CCE.Api.Internal.Program>>,
    IClassFixture<CceTestWebApplicationFactory<CCE.Api.External.Program>>
{
    private readonly CceTestWebApplicationFactory<CCE.Api.Internal.Program> _internal;
    private readonly CceTestWebApplicationFactory<CCE.Api.External.Program> _external;

    public PersonaMatrixTests(
        CceTestWebApplicationFactory<CCE.Api.Internal.Program> @internal,
        CceTestWebApplicationFactory<CCE.Api.External.Program> external)
    {
        _internal = @internal;
        _external = external;
    }

    public enum PersonaOutcome { Allowed, Forbidden, AnonymousUnauthorized }
    public enum ApiHost { Internal, External }

    public static readonly string[] Personas =
    {
        "anonymous", "cce-admin", "cce-editor", "cce-reviewer", "cce-expert", "cce-user",
    };

    /// <summary>
    /// Representative endpoints + per-persona expected outcome. Sourced
    /// from <c>backend/permissions.yaml</c>.
    /// </summary>
    private static readonly (string Label, ApiHost Host, string Path, Dictionary<string, PersonaOutcome> Expected)[] Probes =
    {
        // GET /api/admin/users (User.Read) — admin/editor/reviewer allowed
        ("GET /api/admin/users", ApiHost.Internal, "/api/admin/users", new()
        {
            ["anonymous"]    = PersonaOutcome.AnonymousUnauthorized,
            ["cce-admin"]    = PersonaOutcome.Allowed,
            ["cce-editor"]   = PersonaOutcome.Allowed,
            ["cce-reviewer"] = PersonaOutcome.Allowed,
            ["cce-expert"]   = PersonaOutcome.Forbidden,
            ["cce-user"]     = PersonaOutcome.Forbidden,
        }),

        // GET /api/admin/audit-events (Audit.Read) — admin only
        ("GET /api/admin/audit-events", ApiHost.Internal, "/api/admin/audit-events", new()
        {
            ["anonymous"]    = PersonaOutcome.AnonymousUnauthorized,
            ["cce-admin"]    = PersonaOutcome.Allowed,
            ["cce-editor"]   = PersonaOutcome.Forbidden,
            ["cce-reviewer"] = PersonaOutcome.Forbidden,
            ["cce-expert"]   = PersonaOutcome.Forbidden,
            ["cce-user"]     = PersonaOutcome.Forbidden,
        }),

        // GET /api/admin/expert-requests (Community.Expert.ApproveRequest) — admin/editor/reviewer
        ("GET /api/admin/expert-requests", ApiHost.Internal, "/api/admin/expert-requests", new()
        {
            ["anonymous"]    = PersonaOutcome.AnonymousUnauthorized,
            ["cce-admin"]    = PersonaOutcome.Allowed,
            ["cce-editor"]   = PersonaOutcome.Allowed,
            ["cce-reviewer"] = PersonaOutcome.Allowed,
            ["cce-expert"]   = PersonaOutcome.Forbidden,
            ["cce-user"]     = PersonaOutcome.Forbidden,
        }),

        // /api/me + /api/admin/reports/* probes deferred — those endpoints
        // do additional principal-resolution / route-matching that drops
        // the auth gate test out of pure-401/403/200 territory; the gate
        // itself is exercised by the probes above.
    };

    public static IEnumerable<object[]> AllowedCases() =>
        from probe in Probes
        from kv in probe.Expected
        where kv.Value == PersonaOutcome.Allowed
        select new object[] { probe.Label, probe.Host, probe.Path, kv.Key };

    public static IEnumerable<object[]> ForbiddenCases() =>
        from probe in Probes
        from kv in probe.Expected
        where kv.Value == PersonaOutcome.Forbidden
        select new object[] { probe.Label, probe.Host, probe.Path, kv.Key };

    public static IEnumerable<object[]> AnonymousCases() =>
        Probes.Select(p => new object[] { p.Label, p.Host, p.Path });

    [Theory]
    [MemberData(nameof(AllowedCases))]
    public async Task Allowed_persona_passes_authorization_gate(
        string label, ApiHost host, string path, string persona)
    {
        _ = label; // surfaces in xUnit failure message
        using var client = host == ApiHost.Internal ? _internal.CreateClient() : _external.CreateClient();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", persona);

        var resp = await client.GetAsync(new Uri(path, UriKind.Relative));

        resp.StatusCode.Should().NotBe(HttpStatusCode.Unauthorized,
            $"persona '{persona}' must not get 401 on {label}");
        resp.StatusCode.Should().NotBe(HttpStatusCode.Forbidden,
            $"persona '{persona}' must not get 403 on {label}");
    }

    [Theory]
    [MemberData(nameof(ForbiddenCases))]
    public async Task Forbidden_persona_is_blocked_by_authorization_gate(
        string label, ApiHost host, string path, string persona)
    {
        _ = label;
        using var client = host == ApiHost.Internal ? _internal.CreateClient() : _external.CreateClient();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", persona);

        var resp = await client.GetAsync(new Uri(path, UriKind.Relative));

        resp.StatusCode.Should().Be(HttpStatusCode.Forbidden,
            $"persona '{persona}' lacks permission for {label} and must get 403");
    }

    [Theory]
    [MemberData(nameof(AnonymousCases))]
    public async Task Anonymous_request_returns_401(string label, ApiHost host, string path)
    {
        _ = label;
        using var client = host == ApiHost.Internal ? _internal.CreateClient() : _external.CreateClient();
        // No Authorization header.

        var resp = await client.GetAsync(new Uri(path, UriKind.Relative));

        resp.StatusCode.Should().Be(HttpStatusCode.Unauthorized,
            $"anonymous request to {label} must get 401");
    }
}
