// <auto-generated />
using System;
using CCE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCE.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CceDbContext))]
    partial class CceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCE.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("actor");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Diff")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diff");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("resource");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation_id");

                    b.HasIndex("Actor", "OccurredOn")
                        .HasDatabaseName("ix_audit_events_actor_occurred_on");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasTrigger("trg_audit_events_no_update_delete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CCE.Domain.Community.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnsweredReplyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("answered_reply_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsAnswerable")
                        .HasColumnType("bit")
                        .HasColumnName("is_answerable");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("locale");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_post_topic_id");

                    b.HasIndex("AuthorId", "CreatedOn")
                        .HasDatabaseName("ix_post_author_created");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Community.PostFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FollowedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("followed_on");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("post_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_post_follows");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_post_follow_post_user");

                    b.ToTable("post_follows", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Community.PostRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("post_id");

                    b.Property<DateTimeOffset>("RatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("rated_on");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasColumnName("stars");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_post_ratings");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_post_rating_post_user");

                    b.ToTable("post_ratings", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Community.PostReply", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsByExpert")
                        .HasColumnType("bit")
                        .HasColumnName("is_by_expert");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("locale");

                    b.Property<Guid?>("ParentReplyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_reply_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_post_replies");

                    b.HasIndex("ParentReplyId")
                        .HasDatabaseName("ix_post_reply_parent_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_reply_post_id");

                    b.ToTable("post_replies", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Community.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_en");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_en");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_topic_slug_active")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Community.TopicFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FollowedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("followed_on");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_topic_follows");

                    b.HasIndex("TopicId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_topic_follow_topic_user");

                    b.ToTable("topic_follows", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Community.UserFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FollowedId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("followed_id");

                    b.Property<DateTimeOffset>("FollowedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("followed_on");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("follower_id");

                    b.HasKey("Id")
                        .HasName("pk_user_follows");

                    b.HasIndex("FollowerId", "FollowedId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_follow_follower_followed");

                    b.ToTable("user_follows", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Content.AssetFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTimeOffset?>("ScannedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("scanned_on");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_id");

                    b.Property<DateTimeOffset>("UploadedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("uploaded_on");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("url");

                    b.Property<int>("VirusScanStatus")
                        .HasColumnType("int")
                        .HasColumnName("virus_scan_status");

                    b.HasKey("Id")
                        .HasName("pk_asset_files");

                    b.HasIndex("VirusScanStatus")
                        .HasDatabaseName("ix_asset_file_scan_status");

                    b.ToTable("asset_files", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Content.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_en");

                    b.Property<DateTimeOffset>("EndsOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ends_on");

                    b.Property<string>("FeaturedImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("featured_image_url");

                    b.Property<string>("ICalUid")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("i_cal_uid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LocationAr")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("location_ar");

                    b.Property<string>("LocationEn")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("location_en");

                    b.Property<string>("OnlineMeetingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("online_meeting_url");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("StartsOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("starts_on");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_en");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("ICalUid")
                        .IsUnique()
                        .HasDatabaseName("ux_event_ical_uid");

                    b.HasIndex("StartsOn")
                        .HasDatabaseName("ix_event_starts_on");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Content.HomepageSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContentAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_ar");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_en");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int>("SectionType")
                        .HasColumnType("int")
                        .HasColumnName("section_type");

                    b.HasKey("Id")
                        .HasName("pk_homepage_sections");

                    b.HasIndex("IsActive", "OrderIndex")
                        .HasDatabaseName("ix_homepage_section_active_order");

                    b.ToTable("homepage_sections", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Content.News", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<string>("ContentAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_ar");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_en");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<string>("FeaturedImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("featured_image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("is_featured");

                    b.Property<DateTimeOffset?>("PublishedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_on");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("slug");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_en");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("PublishedOn")
                        .HasDatabaseName("ix_news_published_on");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_news_slug_active")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Content.NewsletterSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("confirmation_token");

                    b.Property<DateTimeOffset?>("ConfirmedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("confirmed_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("LocalePreference")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("locale_preference");

                    b.Property<DateTimeOffset?>("UnsubscribedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("unsubscribed_on");

                    b.HasKey("Id")
                        .HasName("pk_newsletter_subscriptions");

                    b.HasIndex("ConfirmationToken")
                        .HasDatabaseName("ix_newsletter_token");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_newsletter_email");

                    b.ToTable("newsletter_subscriptions", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Content.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContentAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_ar");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_en");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PageType")
                        .HasColumnType("int")
                        .HasColumnName("page_type");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("slug");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_en");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("PageType", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_page_type_slug_active")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Content.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetFileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_file_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_en");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("PublishedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_on");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int")
                        .HasColumnName("resource_type");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_en");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_id");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("AssetFileId")
                        .HasDatabaseName("ix_resource_asset_file_id");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_resource_country_id");

                    b.HasIndex("CategoryId", "PublishedOn")
                        .HasDatabaseName("ix_resource_category_published");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Content.ResourceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_en");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_resource_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_resource_category_parent_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_resource_category_slug");

                    b.ToTable("resource_categories", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Country.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<string>("FlagUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("flag_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("IsoAlpha2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("iso_alpha2");

                    b.Property<string>("IsoAlpha3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("iso_alpha3");

                    b.Property<Guid?>("LatestKapsarcSnapshotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("latest_kapsarc_snapshot_id");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_en");

                    b.Property<string>("RegionAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("region_ar");

                    b.Property<string>("RegionEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("region_en");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("IsoAlpha2")
                        .HasDatabaseName("ix_country_iso_alpha2");

                    b.HasIndex("IsoAlpha3")
                        .IsUnique()
                        .HasDatabaseName("ux_country_iso_alpha3_active")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Country.CountryKapsarcSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("classification");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<decimal>("PerformanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("performance_score");

                    b.Property<DateTimeOffset>("SnapshotTakenOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("snapshot_taken_on");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("source_version");

                    b.Property<decimal>("TotalIndex")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_index");

                    b.HasKey("Id")
                        .HasName("pk_country_kapsarc_snapshots");

                    b.HasIndex("CountryId", "SnapshotTakenOn")
                        .HasDatabaseName("ix_kapsarc_snapshot_country_taken");

                    b.ToTable("country_kapsarc_snapshots", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Country.CountryProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContactInfoAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("contact_info_ar");

                    b.Property<string>("ContactInfoEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("contact_info_en");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_en");

                    b.Property<string>("KeyInitiativesAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key_initiatives_ar");

                    b.Property<string>("KeyInitiativesEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key_initiatives_en");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_updated_by_id");

                    b.Property<DateTimeOffset>("LastUpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_updated_on");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_country_profiles");

                    b.HasIndex("CountryId")
                        .IsUnique()
                        .HasDatabaseName("ux_country_profile_country_id");

                    b.ToTable("country_profiles", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Country.CountryResourceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AdminNotesAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("admin_notes_ar");

                    b.Property<string>("AdminNotesEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("admin_notes_en");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ProcessedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processed_by_id");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_on");

                    b.Property<Guid>("ProposedAssetFileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("proposed_asset_file_id");

                    b.Property<string>("ProposedDescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("proposed_description_ar");

                    b.Property<string>("ProposedDescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("proposed_description_en");

                    b.Property<int>("ProposedResourceType")
                        .HasColumnType("int")
                        .HasColumnName("proposed_resource_type");

                    b.Property<string>("ProposedTitleAr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("proposed_title_ar");

                    b.Property<string>("ProposedTitleEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("proposed_title_en");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requested_by_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_on");

                    b.HasKey("Id")
                        .HasName("pk_country_resource_requests");

                    b.HasIndex("CountryId", "Status")
                        .HasDatabaseName("ix_country_request_country_status");

                    b.ToTable("country_resource_requests", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Identity.ExpertProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AcademicTitleAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("academic_title_ar");

                    b.Property<string>("AcademicTitleEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("academic_title_en");

                    b.Property<Guid>("ApprovedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approved_by_id");

                    b.Property<DateTimeOffset>("ApprovedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("approved_on");

                    b.Property<string>("BioAr")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("bio_ar");

                    b.Property<string>("BioEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("bio_en");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.PrimitiveCollection<string>("ExpertiseTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expertise_tags");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_expert_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_expert_profile_active_user")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("expert_profiles", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Identity.ExpertRegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ProcessedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processed_by_id");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_on");

                    b.Property<string>("RejectionReasonAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("rejection_reason_ar");

                    b.Property<string>("RejectionReasonEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("rejection_reason_en");

                    b.Property<string>("RequestedBioAr")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("requested_bio_ar");

                    b.Property<string>("RequestedBioEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("requested_bio_en");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requested_by_id");

                    b.PrimitiveCollection<string>("RequestedTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requested_tags");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_on");

                    b.HasKey("Id")
                        .HasName("pk_expert_registration_requests");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("ix_expert_request_requested_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_expert_request_status");

                    b.ToTable("expert_registration_requests", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("token_family_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenFamilyId")
                        .HasDatabaseName("ix_refresh_tokens_token_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Identity.StateRepresentativeAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_id");

                    b.Property<DateTimeOffset>("AssignedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("assigned_on");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("RevokedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("revoked_by_id");

                    b.Property<DateTimeOffset?>("RevokedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_state_representative_assignments");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_state_rep_country_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_state_rep_user_id");

                    b.HasIndex("UserId", "CountryId")
                        .IsUnique()
                        .HasDatabaseName("ux_state_rep_active_user_country")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("state_representative_assignments", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<Guid?>("EntraIdObjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entra_id_object_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.PrimitiveCollection<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interests");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("job_title");

                    b.Property<int>("KnowledgeLevel")
                        .HasColumnType("int")
                        .HasColumnName("knowledge_level");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("LocalePreference")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("locale_preference");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("organization_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_users_country_id");

                    b.HasIndex("EntraIdObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_entra_id_object_id")
                        .HasFilter("[entra_id_object_id] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.InteractiveCity.CityScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CityType")
                        .HasColumnType("int")
                        .HasColumnName("city_type");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("configuration_json");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastModifiedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_en");

                    b.Property<int>("TargetYear")
                        .HasColumnType("int")
                        .HasColumnName("target_year");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_city_scenarios");

                    b.HasIndex("UserId", "LastModifiedOn")
                        .HasDatabaseName("ix_city_scenario_user_modified");

                    b.ToTable("city_scenarios", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.InteractiveCity.CityScenarioResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("computed_at");

                    b.Property<int?>("ComputedCarbonNeutralityYear")
                        .HasColumnType("int")
                        .HasColumnName("computed_carbon_neutrality_year");

                    b.Property<decimal>("ComputedTotalCostUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("computed_total_cost_usd");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("engine_version");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scenario_id");

                    b.HasKey("Id")
                        .HasName("pk_city_scenario_results");

                    b.HasIndex("ScenarioId", "ComputedAt")
                        .HasDatabaseName("ix_city_result_scenario_at");

                    b.ToTable("city_scenario_results", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.InteractiveCity.CityTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("CarbonImpactKgPerYear")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("carbon_impact_kg_per_year");

                    b.Property<string>("CategoryAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("category_ar");

                    b.Property<string>("CategoryEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("category_en");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost_usd");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_en");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_en");

                    b.HasKey("Id")
                        .HasName("pk_city_technologies");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_city_tech_is_active");

                    b.ToTable("city_technologies", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.KnowledgeMaps.KnowledgeMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_on");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_en");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_en");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_maps");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_map_slug_active")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("knowledge_maps", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.KnowledgeMaps.KnowledgeMapAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssociatedId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("associated_id");

                    b.Property<int>("AssociatedType")
                        .HasColumnType("int")
                        .HasColumnName("associated_type");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("node_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_map_associations");

                    b.HasIndex("NodeId", "AssociatedType", "AssociatedId")
                        .IsUnique()
                        .HasDatabaseName("ux_km_assoc_node_type_id");

                    b.ToTable("knowledge_map_associations", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.KnowledgeMaps.KnowledgeMapEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_node_id");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("map_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("int")
                        .HasColumnName("relationship_type");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("to_node_id");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_map_edges");

                    b.HasIndex("FromNodeId")
                        .HasDatabaseName("ix_km_edge_from_node");

                    b.HasIndex("ToNodeId")
                        .HasDatabaseName("ix_km_edge_to_node");

                    b.HasIndex("MapId", "FromNodeId", "ToNodeId", "RelationshipType")
                        .IsUnique()
                        .HasDatabaseName("ux_km_edge_map_from_to_relation");

                    b.ToTable("knowledge_map_edges", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.KnowledgeMaps.KnowledgeMapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_en");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("icon_url");

                    b.Property<double>("LayoutX")
                        .HasColumnType("float")
                        .HasColumnName("layout_x");

                    b.Property<double>("LayoutY")
                        .HasColumnType("float")
                        .HasColumnName("layout_y");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("map_id");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_en");

                    b.Property<int>("NodeType")
                        .HasColumnType("int")
                        .HasColumnName("node_type");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_map_nodes");

                    b.HasIndex("MapId", "OrderIndex")
                        .HasDatabaseName("ix_km_node_map_order");

                    b.ToTable("knowledge_map_nodes", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Notifications.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BodyAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_ar");

                    b.Property<string>("BodyEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_en");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("SubjectAr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("subject_ar");

                    b.Property<string>("SubjectEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("subject_en");

                    b.Property<string>("VariableSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("variable_schema_json");

                    b.HasKey("Id")
                        .HasName("pk_notification_templates");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_template_code");

                    b.ToTable("notification_templates", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Notifications.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("ReadOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("read_on");

                    b.Property<string>("RenderedBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rendered_body");

                    b.Property<string>("RenderedLocale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("rendered_locale");

                    b.Property<string>("RenderedSubjectAr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("rendered_subject_ar");

                    b.Property<string>("RenderedSubjectEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("rendered_subject_en");

                    b.Property<DateTimeOffset?>("SentOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("sent_on");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_notifications");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_user_notification_user_status");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Surveys.SearchQueryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("locale");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("query_text");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("int")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("ResultsCount")
                        .HasColumnType("int")
                        .HasColumnName("results_count");

                    b.Property<DateTimeOffset>("SubmittedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_on");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_search_query_logs");

                    b.HasIndex("SubmittedOn")
                        .HasDatabaseName("ix_search_query_log_submitted_on");

                    b.ToTable("search_query_logs", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Surveys.ServiceRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CommentAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("comment_ar");

                    b.Property<string>("CommentEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("comment_en");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("locale");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("page");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset>("SubmittedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_on");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_service_ratings");

                    b.HasIndex("SubmittedOn")
                        .HasDatabaseName("ix_service_rating_submitted_on");

                    b.ToTable("service_ratings", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CCE.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("CCE.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CCE.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CCE.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CCE.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CCE.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("CCE.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CCE.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
