#requires -Version 7.0
<#
.SYNOPSIS
    CCE Sub-10c env-promotion helper.

.DESCRIPTION
    Copies an env-file from one environment to another, rewriting per-env
    values (database name, Sentry environment, IIS hostnames, image tag
    stream, AUTO_ROLLBACK default, log level) to the destination env's
    conventions. Per-env SECRETS (passwords, DSNs, tokens) are intentionally
    blanked out — operator MUST fill them in for the destination env.

    Refuses to overwrite an existing destination file unless -Force is passed.

.PARAMETER FromEnv
    Source environment. One of test, preprod, prod, dr.

.PARAMETER ToEnv
    Destination environment. One of test, preprod, prod, dr.

.PARAMETER ImageTag
    New value for CCE_IMAGE_TAG in the destination. e.g. app-v1.0.0,
    sha-abc1234, latest.

.PARAMETER FromFile
    Source env-file path. Default: C:\ProgramData\CCE\.env.<FromEnv>.

.PARAMETER ToFile
    Destination env-file path. Default: C:\ProgramData\CCE\.env.<ToEnv>.

.PARAMETER Force
    Overwrite the destination if it exists.

.EXAMPLE
    # Promote a test deploy to preprod for QA
    .\deploy\promote-env.ps1 -FromEnv test -ToEnv preprod -ImageTag app-v1.0.0-rc.1

    # Promote a release candidate to prod
    .\deploy\promote-env.ps1 -FromEnv preprod -ToEnv prod -ImageTag app-v1.0.0
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [ValidateSet('test','preprod','prod','dr')] [string]$FromEnv,
    [Parameter(Mandatory)] [ValidateSet('test','preprod','prod','dr')] [string]$ToEnv,
    [Parameter(Mandatory)] [string]$ImageTag,
    [string]$FromFile,
    [string]$ToFile,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

if ($FromEnv -eq $ToEnv) {
    Write-Error "FromEnv and ToEnv must differ."; exit 1
}

if (-not $FromFile) { $FromFile = "C:\ProgramData\CCE\.env.$FromEnv" }
if (-not $ToFile)   { $ToFile   = "C:\ProgramData\CCE\.env.$ToEnv" }

if (-not (Test-Path $FromFile)) {
    Write-Error "Source env-file not found: $FromFile"; exit 1
}
if ((Test-Path $ToFile) -and -not $Force) {
    Write-Error "Destination env-file exists: $ToFile (use -Force to overwrite)"; exit 1
}

# Per-env conventions (kept in lockstep with .env.<env>.example contents).
$envConfig = @{
    'test'    = @{
        DbSuffix       = '_test'
        SentryEnv      = 'test'
        Hostnames      = 'cce-ext-test,cce-admin-panel-test,api.cce-test,api.cce-admin-panel-test'
        AutoRollback   = 'true'
        LogLevel       = 'Debug'
        RequireHttps   = 'false'
        AssistantProv  = 'stub'
    }
    'preprod' = @{
        DbSuffix       = '_preprod'
        SentryEnv      = 'preprod'
        Hostnames      = 'cce-ext-preprod,cce-admin-panel-preprod,api.cce-preprod,api.cce-admin-panel-preprod'
        AutoRollback   = 'true'
        LogLevel       = 'Information'
        RequireHttps   = 'true'
        AssistantProv  = 'anthropic'
    }
    'prod'    = @{
        DbSuffix       = ''
        SentryEnv      = 'production'
        Hostnames      = 'CCE-ext,CCE-admin-Panel,api.CCE,Api.CCE-admin-Panel'
        AutoRollback   = 'false'
        LogLevel       = 'Information'
        RequireHttps   = 'true'
        AssistantProv  = 'anthropic'
    }
    'dr'      = @{
        DbSuffix       = ''
        SentryEnv      = 'dr'
        Hostnames      = 'cce-ext-dr,cce-admin-panel-dr,api.cce-dr,api.cce-admin-panel-dr'
        AutoRollback   = 'false'
        LogLevel       = 'Information'
        RequireHttps   = 'true'
        AssistantProv  = 'anthropic'
    }
}

# Per-env SECRETS that must always be re-filled by the operator on promotion.
# (Re-blanking these is the security feature — an operator who runs
#  `promote-env -ToEnv prod` should NOT accidentally inherit preprod's secrets.)
$secretKeys = @(
    'INFRA_SQL',                  # contains password
    'KEYCLOAK_ADMIN_PASSWORD',
    'LDAP_BIND_PASSWORD',
    'ANTHROPIC_API_KEY',
    'SENTRY_DSN',
    'BACKUP_UNC_PASSWORD',
    'IIS_CERT_PFX_PASSWORD',
    'CCE_GHCR_TOKEN'
)

$toCfg = $envConfig[$ToEnv]
$lines = Get-Content $FromFile

# Mutate.
$newLines = New-Object System.Collections.Generic.List[string]
$newLines.Add("# CCE $ToEnv environment file (Sub-10c)")
$newLines.Add("# Generated by promote-env.ps1 from .env.$FromEnv on $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')")
$newLines.Add("# Operator MUST fill in <set-me> values before deploy.")
$newLines.Add("")

foreach ($line in $lines) {
    if ($line -match '^\s*#') { $newLines.Add($line); continue }
    if ($line -match '^\s*$') { $newLines.Add($line); continue }

    if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
        $key = $Matches[1]
        $rest = $Matches[2]

        # Re-blank secrets.
        if ($secretKeys -contains $key) {
            $newLines.Add("$key=<set-me>")
            continue
        }

        # Per-env knobs.
        switch ($key) {
            'CCE_IMAGE_TAG'                 { $newLines.Add("$key=$ImageTag");                continue }
            'INFRA_SQL'                     { $newLines.Add("$key=<set-me>");                 continue }   # contains password
            'IIS_HOSTNAMES'                 { $newLines.Add("$key=$($toCfg.Hostnames)");      continue }
            'KEYCLOAK_REQUIRE_HTTPS'        { $newLines.Add("$key=$($toCfg.RequireHttps)");   continue }
            'ASSISTANT_PROVIDER'            { $newLines.Add("$key=$($toCfg.AssistantProv)");  continue }
            'LOG_LEVEL'                     { $newLines.Add("$key=$($toCfg.LogLevel)");       continue }
            'SENTRY_ENVIRONMENT'            { $newLines.Add("$key=$($toCfg.SentryEnv)");      continue }
            'SENTRY_RELEASE'                { $newLines.Add("$key=$ImageTag");                continue }
            'AUTO_ROLLBACK'                 { $newLines.Add("$key=$($toCfg.AutoRollback)");   continue }
            'KEYCLOAK_AUTHORITY' {
                # https://api.CCE-<env>/auth/realms/cce
                $hostname = if ($ToEnv -eq 'prod') { 'api.CCE' } else { "api.cce-$ToEnv" }
                $newLines.Add("$key=https://$hostname/auth/realms/cce")
                continue
            }
        }

        # Default: keep as-is.
        $newLines.Add($line)
    } else {
        $newLines.Add($line)
    }
}

# Atomic write.
$tempFile = "$ToFile.tmp"
$newLines | Set-Content -Path $tempFile -Encoding utf8
Move-Item -Path $tempFile -Destination $ToFile -Force

Write-Host "Wrote $ToFile (promoted from .env.$FromEnv with CCE_IMAGE_TAG=$ImageTag)."
Write-Host ""
Write-Host "REMAINING OPERATOR STEPS:" -ForegroundColor Yellow
Write-Host "  1. Fill in <set-me> values in $ToFile (secrets, IIS_CERT_*)." -ForegroundColor Yellow
Write-Host "  2. Run validate-env.ps1 to confirm no placeholders remain:" -ForegroundColor Yellow
Write-Host "       .\deploy\validate-env.ps1 -EnvFile $ToFile -Environment $ToEnv" -ForegroundColor Yellow
Write-Host "  3. Lock down ACLs:" -ForegroundColor Yellow
Write-Host "       icacls $ToFile /inheritance:r /grant:r 'Administrators:R' '<deploy-user>:R'" -ForegroundColor Yellow
Write-Host "  4. Deploy:  .\deploy\deploy.ps1 -Environment $ToEnv" -ForegroundColor Yellow
exit 0
