using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CCE.Domain.SourceGenerators;

/// <summary>
/// Roslyn incremental source generator that turns <c>backend/permissions.yaml</c> into a
/// strongly-typed <see cref="Permissions"/> static class in <c>CCE.Domain</c>.
/// Triggered automatically on every build of any project that adds this generator as an analyzer
/// and adds <c>permissions.yaml</c> as an <c>AdditionalFiles</c> item.
/// </summary>
[Generator]
public sealed class PermissionsGenerator : IIncrementalGenerator
{
    private const string YamlFileName = "permissions.yaml";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Match permissions.yaml under any path. Compare by filename so subdirectory layout
        // (backend/permissions.yaml vs ./permissions.yaml) doesn't matter to the generator.
        var yamlContent = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(YamlFileName, StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => file.GetText(ct)?.ToString() ?? string.Empty)
            .Collect();

        context.RegisterSourceOutput(yamlContent, static (spc, contents) =>
        {
            // If multiple permissions.yaml files match (shouldn't happen but defensive), use the first non-empty.
            var yaml = contents.FirstOrDefault(c => !string.IsNullOrWhiteSpace(c)) ?? string.Empty;
            var permissions = ParsePermissions(yaml);
            var source = GenerateSource(permissions);
            spc.AddSource("Permissions.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Hand-rolled parser for the flat-list YAML format used by <c>permissions.yaml</c>.
    /// Recognizes lines of the form <c>  - Some.Permission.Name</c> (inside a top-level list).
    /// Ignores blank lines, comment lines (starting with <c>#</c>), and the <c>permissions:</c> header.
    /// Quotes around the name are stripped.
    /// </summary>
    private static List<string> ParsePermissions(string yaml)
    {
        var result = new List<string>();
        if (string.IsNullOrWhiteSpace(yaml))
        {
            return result;
        }

        foreach (var raw in yaml.Split('\n'))
        {
            var line = raw.Trim();
            if (line.Length == 0)
            {
                continue;
            }
            if (line[0] == '#')
            {
                continue;
            }
            if (!line.StartsWith("- ", StringComparison.Ordinal))
            {
                continue;
            }
            var name = line.Substring(2).Trim().Trim('"', '\'').Trim();
            if (name.Length == 0)
            {
                continue;
            }
            // Defensive validation: only accept dot-separated PascalCase tokens.
            if (!IsValidPermissionName(name))
            {
                continue;
            }
            result.Add(name);
        }
        return result;
    }

    private static bool IsValidPermissionName(string name)
    {
        var segments = name.Split('.');
        if (segments.Length < 2)
        {
            return false;
        }
        foreach (var seg in segments)
        {
            if (seg.Length == 0)
            {
                return false;
            }
            if (!char.IsUpper(seg[0]))
            {
                return false;
            }
            for (var i = 1; i < seg.Length; i++)
            {
                var c = seg[i];
                if (!char.IsLetterOrDigit(c))
                {
                    return false;
                }
            }
        }
        return true;
    }

    private static string GenerateSource(List<string> permissions)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by CCE.Domain.SourceGenerators.PermissionsGenerator from permissions.yaml.");
        sb.AppendLine("//   DO NOT EDIT — change the YAML and rebuild.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace CCE.Domain;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Strongly-typed permission name constants generated from <c>permissions.yaml</c>.");
        sb.AppendLine("/// Use these constants in policy registrations and <c>[RequirePermission(...)]</c> attributes.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Permissions");
        sb.AppendLine("{");

        foreach (var p in permissions)
        {
            var memberName = ToMemberName(p);
            sb.AppendLine($"    /// <summary>The <c>{p}</c> permission.</summary>");
            sb.AppendLine($"    public const string {memberName} = \"{p}\";");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>Every permission, in YAML declaration order.</summary>");
        sb.AppendLine("    public static IReadOnlyList<string> All { get; } = new[]");
        sb.AppendLine("    {");
        foreach (var p in permissions)
        {
            sb.AppendLine($"        {ToMemberName(p)},");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToMemberName(string permission) => permission.Replace('.', '_');
}
