/**
 * Curated dataset of 60 major world cities with sustainability /
 * carbon-economy metadata. Used by the WorldMapComponent to render
 * clickable markers on the D3 world map.
 *
 * Coordinates are decimal lat/lon (WGS84). Population values are
 * rough metro-area figures rounded to the nearest hundred-thousand.
 * Carbon-intensity tiers are qualitative for the demo dataset.
 */

export type CarbonTier = 'low' | 'medium' | 'high';

export interface City {
  readonly id: string;
  readonly name: string;
  readonly country: string;
  readonly countryCode: string; // ISO 3166-1 alpha-2
  readonly lat: number;
  readonly lon: number;
  readonly population: number;
  readonly carbonTier: CarbonTier;
  readonly summary: string;
  readonly initiatives: readonly string[];
}

export const CITIES: readonly City[] = [
  {
    id: 'riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 24.7136,
    lon: 46.6753,
    population: 7600000,
    carbonTier: 'medium',
    summary:
      'Capital of Saudi Arabia and host of the Carbon Circular Economy initiative. Major investments in green hydrogen and solar.',
    initiatives: ['NEOM Green Hydrogen', 'Saudi Green Initiative', 'Sakaka PV Plant'],
  },
  {
    id: 'jeddah',
    name: 'Jeddah',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 21.4858,
    lon: 39.1925,
    population: 4700000,
    carbonTier: 'medium',
    summary:
      "Saudi Arabia's commercial hub on the Red Sea. Host of regional sustainability summits.",
    initiatives: ['Red Sea Project', 'Jeddah Tower (sustainable design)'],
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    lat: 25.2048,
    lon: 55.2708,
    population: 3600000,
    carbonTier: 'medium',
    summary:
      'Hosted COP28 in 2023. Mohammed bin Rashid Al Maktoum Solar Park is one of the largest single-site solar parks in the world.',
    initiatives: ['Mohammed bin Rashid Solar Park', 'Dubai Net Zero 2050'],
  },
  {
    id: 'cairo',
    name: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    lat: 30.0444,
    lon: 31.2357,
    population: 22000000,
    carbonTier: 'high',
    summary:
      'Hosted COP27 in 2022. Benban Solar Park (1.8 GW) demonstrates Egypt’s renewable scale-up.',
    initiatives: ['Benban Solar Park', 'New Administrative Capital'],
  },
  {
    id: 'doha',
    name: 'Doha',
    country: 'Qatar',
    countryCode: 'QA',
    lat: 25.2854,
    lon: 51.531,
    population: 2400000,
    carbonTier: 'medium',
    summary:
      "Qatar's capital; commitments to LNG carbon-capture and post-2022-World-Cup green legacy.",
    initiatives: ['Al Kharsaah Solar PV', 'Carbon Capture LNG'],
  },
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.5074,
    lon: -0.1278,
    population: 9500000,
    carbonTier: 'low',
    summary:
      "Ultra Low Emission Zone covers all 32 boroughs. Heat networks and carbon-pricing leadership.",
    initiatives: ['ULEZ', 'London Heat Network', 'Net Zero by 2030'],
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    lat: 48.8566,
    lon: 2.3522,
    population: 11200000,
    carbonTier: 'low',
    summary:
      'Paris Climate Agreement namesake city. Aggressive cycling-infra rollout and the 15-minute-city concept.',
    initiatives: ['15-Minute City', 'Plan Vélo'],
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    lat: 52.52,
    lon: 13.405,
    population: 3700000,
    carbonTier: 'low',
    summary:
      'European leader in district heating from waste heat. Klimaschutzgesetz mandates 2045 net-zero.',
    initiatives: ['Klimaschutzgesetz 2045', 'Berlin District Heating'],
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    lat: 52.3676,
    lon: 4.9041,
    population: 1200000,
    carbonTier: 'low',
    summary:
      'Doughnut Economics framework adopted city-wide. Aggressive bike-first urbanism.',
    initiatives: ['Doughnut Economics', 'Amsterdam Climate Neutral 2050'],
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    lat: 55.6761,
    lon: 12.5683,
    population: 1400000,
    carbonTier: 'low',
    summary:
      'Targeting CO2-neutrality by 2025; the most cycled-to-work capital in the EU.',
    initiatives: ['CPH 2025 Climate Plan', 'Cycle Superhighways'],
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    lat: 59.3293,
    lon: 18.0686,
    population: 1700000,
    carbonTier: 'low',
    summary:
      'Royal Seaport eco-district pilot. Stockholm Exergi runs the world’s largest BECCS pilot.',
    initiatives: ['Royal Seaport', 'Stockholm Exergi BECCS'],
  },
  {
    id: 'oslo',
    name: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    lat: 59.9139,
    lon: 10.7522,
    population: 1100000,
    carbonTier: 'low',
    summary:
      'Highest EV adoption rate of any major city. Klemetsrud waste-to-energy CCS by 2026.',
    initiatives: ['EV-First Capital', 'Klemetsrud CCS'],
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    lat: 40.4168,
    lon: -3.7038,
    population: 6700000,
    carbonTier: 'medium',
    summary:
      'Madrid 360 plan restricts polluting vehicles in the M30 ring. Solar rollout accelerating.',
    initiatives: ['Madrid 360', 'Solar PV scheme'],
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    lat: 41.9028,
    lon: 12.4964,
    population: 4300000,
    carbonTier: 'medium',
    summary:
      'PNRR-funded urban-greening + electric-bus rollout. Targeting 2030 emissions cut.',
    initiatives: ['PNRR Green Transition'],
  },
  {
    id: 'moscow',
    name: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.7558,
    lon: 37.6176,
    population: 12500000,
    carbonTier: 'high',
    summary:
      'Massive district-heating system; carbon-intensity high due to gas-heavy mix. Gradual fleet electrification.',
    initiatives: ['Moscow Electric Bus Fleet'],
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Türkiye',
    countryCode: 'TR',
    lat: 41.0082,
    lon: 28.9784,
    population: 15800000,
    carbonTier: 'high',
    summary:
      'Bridge between continents; major investments in metro expansion + green-bond issuance.',
    initiatives: ['Marmaray Tunnel', 'Green Bond Framework'],
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    lat: -33.9249,
    lon: 18.4241,
    population: 4700000,
    carbonTier: 'medium',
    summary:
      'Day-Zero water crisis (2018) drove a global lesson in demand management. Renewables IPP procurement leading the continent.',
    initiatives: ['REIPPPP', 'Cape Town Water Strategy'],
  },
  {
    id: 'lagos',
    name: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    lat: 6.5244,
    lon: 3.3792,
    population: 21000000,
    carbonTier: 'high',
    summary:
      'Africa’s most populous city. Lagos Climate Action Plan + BRT expansion.',
    initiatives: ['Lagos Climate Action Plan', 'Bus Rapid Transit'],
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    lat: -1.2921,
    lon: 36.8219,
    population: 5100000,
    carbonTier: 'medium',
    summary:
      "Hosted Africa Climate Summit 2023. Kenya's grid is ~90% renewable (geothermal + hydro).",
    initiatives: ['Africa Climate Summit', 'Olkaria Geothermal'],
  },
  {
    id: 'addis-ababa',
    name: 'Addis Ababa',
    country: 'Ethiopia',
    countryCode: 'ET',
    lat: 9.03,
    lon: 38.74,
    population: 5400000,
    carbonTier: 'medium',
    summary:
      'Africa’s diplomatic capital; Ethiopian Airlines hub piloting SAF. GERD hydropower nearing full capacity.',
    initiatives: ['GERD Hydropower', 'Addis BRT'],
  },
  {
    id: 'casablanca',
    name: 'Casablanca',
    country: 'Morocco',
    countryCode: 'MA',
    lat: 33.5731,
    lon: -7.5898,
    population: 4400000,
    carbonTier: 'medium',
    summary:
      "Morocco's economic center. Noor Ouarzazate (~580 MW) is the world's largest concentrated-solar plant.",
    initiatives: ['Noor Ouarzazate CSP', 'Tramway expansion'],
  },
  {
    id: 'new-york',
    name: 'New York',
    country: 'United States',
    countryCode: 'US',
    lat: 40.7128,
    lon: -74.006,
    population: 18800000,
    carbonTier: 'medium',
    summary:
      'Local Law 97 caps building emissions. Congestion-pricing scheme active in Manhattan.',
    initiatives: ['Local Law 97', 'Manhattan Congestion Pricing'],
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    country: 'United States',
    countryCode: 'US',
    lat: 34.0522,
    lon: -118.2437,
    population: 13200000,
    carbonTier: 'high',
    summary:
      'Aggressive port-of-LA electrification. LA100 plan: 100% renewable electricity by 2035.',
    initiatives: ['LA100 Plan', 'Port Electrification'],
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    country: 'United States',
    countryCode: 'US',
    lat: 37.7749,
    lon: -122.4194,
    population: 4700000,
    carbonTier: 'low',
    summary:
      'First major US city with mandatory composting. Climate-tech VC capital of the world.',
    initiatives: ['Mandatory Composting', 'Climate-Tech Ecosystem'],
  },
  {
    id: 'chicago',
    name: 'Chicago',
    country: 'United States',
    countryCode: 'US',
    lat: 41.8781,
    lon: -87.6298,
    population: 9500000,
    carbonTier: 'medium',
    summary:
      'Climate Action Plan targets 62% emissions reduction by 2040. Smart streetlight rollout.',
    initiatives: ['Climate Action Plan'],
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    countryCode: 'CA',
    lat: 43.6532,
    lon: -79.3832,
    population: 6500000,
    carbonTier: 'medium',
    summary:
      'TransformTO net-zero strategy. Ontario grid mostly nuclear + hydro.',
    initiatives: ['TransformTO', 'Pickering Nuclear Refurbishment'],
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    lat: 49.2827,
    lon: -123.1207,
    population: 2600000,
    carbonTier: 'low',
    summary:
      'Greenest City Action Plan made it the highest-rated North American city for sustainability.',
    initiatives: ['Greenest City Action Plan', 'False Creek Energy'],
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    lat: 19.4326,
    lon: -99.1332,
    population: 22000000,
    carbonTier: 'high',
    summary:
      'Air-quality + water-stress challenges driving urban-greening programs.',
    initiatives: ['Cablebús Metrocable', 'Urban Reforestation'],
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    countryCode: 'CO',
    lat: 4.711,
    lon: -74.0721,
    population: 11000000,
    carbonTier: 'medium',
    summary:
      "TransMilenio BRT + RegioTram regional rail. Cycle network expanding rapidly.",
    initiatives: ['TransMilenio BRT', 'CicloRutas'],
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    lat: -23.5505,
    lon: -46.6333,
    population: 22500000,
    carbonTier: 'medium',
    summary:
      'Largest city in the southern hemisphere. Brazil’s grid is ~80% renewable (hydro-heavy).',
    initiatives: ['Linha 6 Metro', 'Plano Municipal Mudança do Clima'],
  },
  {
    id: 'rio-de-janeiro',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    lat: -22.9068,
    lon: -43.1729,
    population: 13700000,
    carbonTier: 'medium',
    summary:
      'C40 Mayors host. Climate-resilience focus on coastal protection.',
    initiatives: ['Plano de Adaptação Climática'],
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    lat: -34.6037,
    lon: -58.3816,
    population: 16200000,
    carbonTier: 'medium',
    summary:
      'Metrobús network expanded; LED-streetlight conversion complete.',
    initiatives: ['Metrobús BRT', 'Plan Climático 2050'],
  },
  {
    id: 'santiago',
    name: 'Santiago',
    country: 'Chile',
    countryCode: 'CL',
    lat: -33.4489,
    lon: -70.6693,
    population: 7000000,
    carbonTier: 'medium',
    summary:
      'Largest electric-bus fleet in Latin America. Chile leads green-hydrogen exports.',
    initiatives: ['Red Metropolitana de Movilidad', 'Green H2 Strategy'],
  },
  {
    id: 'lima',
    name: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    lat: -12.0464,
    lon: -77.0428,
    population: 11000000,
    carbonTier: 'medium',
    summary:
      'Coastal desert city; water-stress innovation via fog-collection trials.',
    initiatives: ['Lima Metro Line 2', 'Fog Catchers'],
  },
  {
    id: 'beijing',
    name: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    lat: 39.9042,
    lon: 116.4074,
    population: 21500000,
    carbonTier: 'high',
    summary:
      "China's capital; aggressive coal-to-gas conversion + EV-only new taxi fleet.",
    initiatives: ['EV Taxi Fleet', 'Coal-to-Gas Heating'],
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    lat: 31.2304,
    lon: 121.4737,
    population: 28500000,
    carbonTier: 'high',
    summary:
      'World’s largest port + carbon-emissions trading scheme pilot. CATL + LFP battery hub.',
    initiatives: ['Shanghai ETS', 'Lin-gang Free Trade Zone'],
  },
  {
    id: 'shenzhen',
    name: 'Shenzhen',
    country: 'China',
    countryCode: 'CN',
    lat: 22.5431,
    lon: 114.0579,
    population: 17500000,
    carbonTier: 'medium',
    summary:
      'First major city with 100%-electric public bus fleet (16,000+ buses).',
    initiatives: ['100% E-Bus Fleet', 'BYD HQ'],
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    country: 'Hong Kong SAR',
    countryCode: 'HK',
    lat: 22.3193,
    lon: 114.1694,
    population: 7500000,
    carbonTier: 'medium',
    summary:
      'Climate Action Plan 2050; aggressive electrification of franchised buses.',
    initiatives: ['CAP 2050', 'Carbon Neutrality 2050'],
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.6762,
    lon: 139.6503,
    population: 37400000,
    carbonTier: 'medium',
    summary:
      'World’s largest metro region. Cap-and-trade for buildings; hydrogen society plan.',
    initiatives: ['Tokyo Cap-and-Trade', 'Hydrogen Society'],
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    lat: 37.5665,
    lon: 126.978,
    population: 25700000,
    carbonTier: 'medium',
    summary:
      'Cheonggyecheon stream restoration set the tone for global green-corridor projects.',
    initiatives: ['Cheonggyecheon Stream', 'Green New Deal'],
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    lat: 1.3521,
    lon: 103.8198,
    population: 5900000,
    carbonTier: 'medium',
    summary:
      'Green Plan 2030 + S$5b Coastal & Flood Protection Fund. ASEAN sustainability hub.',
    initiatives: ['Green Plan 2030', 'Tuas Mega Port'],
  },
  {
    id: 'jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    lat: -6.2088,
    lon: 106.8456,
    population: 33000000,
    carbonTier: 'high',
    summary:
      'Sinking-city challenge driving Nusantara new-capital project. MRT + LRT expansion.',
    initiatives: ['Nusantara New Capital', 'MRT Phase 2'],
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    lat: 19.076,
    lon: 72.8777,
    population: 21300000,
    carbonTier: 'high',
    summary:
      'Mumbai Climate Action Plan first sub-national plan in India aligned to net-zero by 2050.',
    initiatives: ['Mumbai Climate Action Plan', 'Coastal Road Project'],
  },
  {
    id: 'delhi',
    name: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    lat: 28.6139,
    lon: 77.209,
    population: 32900000,
    carbonTier: 'high',
    summary:
      'Air-quality crisis driving the world’s largest electric-bus tender. Solar rooftop expansion.',
    initiatives: ['Delhi EV Policy', 'GRAP Air-Quality Action'],
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    lat: 13.7563,
    lon: 100.5018,
    population: 10700000,
    carbonTier: 'high',
    summary:
      'BTS / MRT extensions reshape commuting patterns. Flood-resilience parks pioneered locally.',
    initiatives: ['Centenary Park', 'BTS Green Line Extension'],
  },
  {
    id: 'ho-chi-minh',
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    lat: 10.8231,
    lon: 106.6297,
    population: 13300000,
    carbonTier: 'medium',
    summary:
      'Vietnam’s commercial center; rapid solar rooftop adoption + EV market growth.',
    initiatives: ['Metro Line 1', 'Net-Zero by 2050'],
  },
  {
    id: 'manila',
    name: 'Manila',
    country: 'Philippines',
    countryCode: 'PH',
    lat: 14.5995,
    lon: 120.9842,
    population: 14400000,
    carbonTier: 'high',
    summary:
      'Climate-vulnerable archipelago capital; renewables-portfolio-standard accelerating.',
    initiatives: ['Renewable Energy Act', 'EDSA Bus Carousel'],
  },
  {
    id: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    lat: 3.139,
    lon: 101.6869,
    population: 8200000,
    carbonTier: 'medium',
    summary:
      'KL Low Carbon Society Blueprint targets 70% emissions cut by 2030.',
    initiatives: ['KL Low Carbon Society Blueprint'],
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    lat: -33.8688,
    lon: 151.2093,
    population: 5400000,
    carbonTier: 'medium',
    summary:
      'Net-zero Council operations since 2007. Offshore-wind precinct under planning.',
    initiatives: ['Net Zero City Operations', 'Offshore Wind Precinct'],
  },
  {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    countryCode: 'AU',
    lat: -37.8136,
    lon: 144.9631,
    population: 5100000,
    carbonTier: 'medium',
    summary:
      "Melbourne Renewable Energy Project 2: largest local-government PPA in Australia.",
    initiatives: ['MREP2 PPA', 'Climate Emergency Declaration'],
  },
  {
    id: 'auckland',
    name: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    lat: -36.8485,
    lon: 174.7633,
    population: 1700000,
    carbonTier: 'low',
    summary:
      "Te Tāruke-ā-Tāwhiri Climate Plan; aggressive bus electrification.",
    initiatives: ['Te Tāruke-ā-Tāwhiri Plan', 'Bus Electrification'],
  },
  {
    id: 'wellington',
    name: 'Wellington',
    country: 'New Zealand',
    countryCode: 'NZ',
    lat: -41.2865,
    lon: 174.7762,
    population: 420000,
    carbonTier: 'low',
    summary:
      'Net-zero by 2050 in legislation. Strong wind-power capacity.',
    initiatives: ['Te Atakura Climate Action Plan'],
  },
  {
    id: 'tehran',
    name: 'Tehran',
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lon: 51.389,
    population: 9100000,
    carbonTier: 'high',
    summary:
      'Energy-subsidy reform debate; metro expansion + air-quality action.',
    initiatives: ['Tehran Metro Expansion'],
  },
  {
    id: 'karachi',
    name: 'Karachi',
    country: 'Pakistan',
    countryCode: 'PK',
    lat: 24.8607,
    lon: 67.0011,
    population: 16800000,
    carbonTier: 'high',
    summary:
      "Pakistan's commercial center; mega heat-action plans + BRT corridors.",
    initiatives: ['Karachi BRT Green Line', 'Heat Action Plan'],
  },
  {
    id: 'tel-aviv',
    name: 'Tel Aviv',
    country: 'Israel',
    countryCode: 'IL',
    lat: 32.0853,
    lon: 34.7818,
    population: 4400000,
    carbonTier: 'medium',
    summary:
      'Light-rail Red Line opened 2023; cleantech investment hub.',
    initiatives: ['Tel Aviv Light Rail', 'Cleantech Ecosystem'],
  },
  {
    id: 'amman',
    name: 'Amman',
    country: 'Jordan',
    countryCode: 'JO',
    lat: 31.9454,
    lon: 35.9284,
    population: 4500000,
    carbonTier: 'medium',
    summary:
      'Water-scarcity capital; pioneering solar at scale (Jordan = Middle-East solar leader).',
    initiatives: ['Disi Water Conveyance', 'Quweira Solar Plant'],
  },
  {
    id: 'kuwait-city',
    name: 'Kuwait City',
    country: 'Kuwait',
    countryCode: 'KW',
    lat: 29.3759,
    lon: 47.9774,
    population: 3100000,
    carbonTier: 'high',
    summary:
      'Shagaya Renewable Energy Park stage targets 15% renewables by 2030.',
    initiatives: ['Shagaya Renewable Energy Park'],
  },
  {
    id: 'manama',
    name: 'Manama',
    country: 'Bahrain',
    countryCode: 'BH',
    lat: 26.2235,
    lon: 50.5876,
    population: 700000,
    carbonTier: 'high',
    summary:
      'Net-Zero 2060 commitment; Bahrain Bay green-tech demonstrator.',
    initiatives: ['Net-Zero 2060', 'Bahrain Bay Master Plan'],
  },
  {
    id: 'muscat',
    name: 'Muscat',
    country: 'Oman',
    countryCode: 'OM',
    lat: 23.5859,
    lon: 58.4059,
    population: 1500000,
    carbonTier: 'high',
    summary:
      'Oman 2040 Vision targets 30% renewables; Hyport Duqm green-hydrogen export hub.',
    initiatives: ['Oman 2040 Vision', 'Hyport Duqm'],
  },
];
